### ISSUE TITLE
FAILURE: Lets Give the Test Cases a Try "/Users/ethers/my-app> npm test"

### ISSUE THREAD

**Issue by cohabo** [ethers-io/ethers.io#15]
Hi Ric,

I cant for the love of me get this to work, both from linux bash or powershell environments, and even trying to directly include the /lib directly into the ethereumjs-vm folder didn't help,  things broke out into a compiler error. Kindly assist.

> ethers-tutorial-token@0.0.1 test /home/cohabo/ethers/my-app
> mocha test-token.js --timeout 100000

module.js:538
    throw err;
    ^

Error: Cannot find module 'ethereumjs-vm/lib/hooked'
    at Function.Module._resolveFilename (module.js:536:15)
    at Function.Module._load (module.js:466:25)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cohabo/ethers/my-app/node_modules/ethers-cli/lib/test-provider.js:11:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cohabo/ethers/my-app/node_modules/ethers-cli/lib/builders.js:14:20)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cohabo/ethers/my-app/node_modules/ethers-cli/index.js:3:16)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/cohabo/ethers/my-app/test-token.js:6:13)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Module.require (module.js:579:17)
    at require (internal/module.js:11:18)
    at /home/cohabo/ethers/my-app/node_modules/mocha/lib/mocha.js:231:27
    at Array.forEach (<anonymous>)
    at Mocha.loadFiles (/home/cohabo/ethers/my-app/node_modules/mocha/lib/mocha.js:228:14)
    at Mocha.run (/home/cohabo/ethers/my-app/node_modules/mocha/lib/mocha.js:514:10)
    at Object.<anonymous> (/home/cohabo/ethers/my-app/node_modules/mocha/bin/_mocha:480:18)
    at Module._compile (module.js:635:30)
    at Object.Module._extensions..js (module.js:646:10)
    at Module.load (module.js:554:32)
    at tryModuleLoad (module.js:497:12)
    at Function.Module._load (module.js:489:3)
    at Function.Module.runMain (module.js:676:10)
    at startup (bootstrap_node.js:187:16)
    at bootstrap_node.js:608:3
npm ERR! Test failed.  See above for more details.
:~/ethers/my-app$

**Comment by ricmoo** [comment]
Make sure you upgrade to the latest version. This was recently fixed...

**Comment by ricmoo** [comment]
(they moved the file from lib to dist)

**Comment by cohabo** [comment]
Hi,

Will require the latest version of, below is my setup, thanks?

npm ERR! Test failed.  See above for more details.

\token-tutorial\my-app>node -v
v8.9.3

\token-tutorial\my-app>npm -v
5.8.0

**Comment by ricmoo** [comment]
Sorry, I meant the latest version of `ethers-cli`. Make sure you remove the `package-lock.json` file before doing a `npm install` to get the latest version. The package-lock.json file may be ignoring the `^3.0.4` part of your package.json. You can check the version by looking at `node_modules/ethers-cli/pacakge.json`.

If you do have the latest version, can you send me (if you prefer not publicly posting it, you can send it to support@ethers.io) the test file you are trying to run?

**Comment by cohabo** [comment]
Hi,

Still getting the same response even after delete and fresh install, this is my setup now:
},
  "dependencies": {
    "ethers": "^3.0.9",
    "ethers-cli": "^3.0.4"
  },
  "devDependencies": {
    "mocha": "^5.0.5"
  },


I am for starters trying to run the token-tutorial in https://cdn.ethers.io/tutorials/token-tutorial.zip

    1) "before each" hook for "mints tokens to a call to mint"


  0 passing (6s)
  1 failing

  1) "before each" hook for "mints tokens to a call to mint":
     Error: compiler error
      at _compile (node_modules\ethers-cli\lib\compiler.js:231:21)
      at compile (node_modules\ethers-cli\lib\compiler.js:415:12)
      at C:\Users\ohabo\Workspaces\ethers\my-app\node_modules\ethers-cli\lib\compiler.js:303:22
      at addDebugging (node_modules\ethers-cli\lib\compiler.js:311:7)
      at loadSource (node_modules\ethers-cli\lib\compiler.js:423:22)
      at _compile (node_modules\ethers-cli\lib\compiler.js:227:25)
      at TestBuilder.testCompile [as _compile] (node_modules\ethers-cli\lib\compiler.js:428:12)
      at TestBuilder.Builder.compile (node_modules\ethers-cli\lib\builders.js:60:27)
      at TestBuilder.compile (node_modules\ethers-cli\lib\builders.js:188:44)
      at TestBuilder.deploy [as _deploy] (deploy-token.js:17:25)
      at C:\Users\ohabo\Workspaces\ethers\my-app\node_modules\ethers-cli\lib\builders.js:154:35
      at <anonymous>
      at process._tickCallback (internal/process/next_tick.js:188:7)



npm ERR! Test failed.  See above for more details.

**Comment by ricmoo** [comment]
Closing this, since the new tutorial should not have this issue. If you are still having problems, please feel free to re-open.

Thanks! :)
